language: ruby
install:
  - bundle install
env:
  global:
    secure: >
      "A4alyrcNGjhvLNsgwZZctOnElkxSYLWEWA4QyZeBVy/3vZGZGNy0ju4VgZLKKwv7BxQkM7TBnBdTipl4DYwcXqIpQjSkCcdGuUN2y8Ia7fiKxFsiKXEHOQ8rWr2NEb3sg1J3BzS/TDDAbosMETU7y/iHDwjcApjX1LmNQ5Gmnz7JfoB1lSznhosvH085o4E3rWPst35g4TOxvLYsxIv3iOgTXwacNmUiynXLAfwwFL+G0Pl7TFjd8ziM9RgRrCLMjhkcjK9ZYV+SH4pAxNeI6+Zrl6rOHO+Ul4WUHxq2VYInrvnDDBsC3jc9uU+7WmX5UkgSY6wxgCPUd2ueDX6o6669pJw1lmTz6CvYPq5sWscYpI/MudT4JgS/+8KcBiSNQ8mqVJfv0WSZiUyaQarJBa9SE29xPSsvq3aXQ54kOBlqoaXOGHiGDnTS2GOwabs+ve9zaZQu3K7B2BdLcUggtgfz5eoVNLBTgw32uD7zij5Rs4DzQGCdP6hMqo9IGhSiga64vPNosthLjEQr/fzQUeWm4jNPHKw+Z/MunX3xlh5c9KrcYhk7BSMsxH2kb6kvkot7TqlSz8QxWWdbc+qfnq+ZKkvTY6zkTv7QXy+W36wQUNqTDRq9uogAGeIbts8x3xpAoIERM/6lMnSblUCC6p0Fh80Sgz+vnGSt/HhEZFk="
