language: ruby
install:
  - bundle install
script: 'bundle exec rake site:deploy --quiet'
env:
  global:
    secure: >
      "5dmxo1nrkiom1Bb83Nzw7RlcvQfCy4vlCgzSKgOe2X0XH7fmD8lt7CsfKALDw1jWRlg6TzCVBfhcxs2NgDWQk9yEEi6qxp/y8qKs5/V5EHU57Ay4xdtvXQmgvXuZQ0HsJjunsgcNfV/sdVzb6RLr40torDgNNj/Gq+KDiUqwnJcUwlNgKTWEDx2qpFmmfoAFGXVWyngYALIgToadSFNzN5oIEFQcL11tx3sdXfJH81HsRR6JtO2yVfb4KOI+fbgFGpzfJROfDfCmILBaALFlk15vSlBjq+jTIxWjvyvhRMiCyOlcbmJpjvz78sIOrC/lcXIjeUngrHiI1PXz5qvjAWeCXibtI07ZKGxvuquYG8zVQSiY7j/r0rwv3hANtFTm7DzKD7ws7nDy1bD4MpsiPDxiNDWbrt8VKAffuwkhrQOI30u2nZqbTA+E4mvhTrgqtR+XGfBu7thoHSE5LEWRwg5V9hMi/NwfMqbhQQ0Lc8yiA/lrpLP6ma4AzUjncHOTDuIk9i7F79dwUkclPd2LyQ/kLF0Q0TFh+zw97y6nBOL//kvqEe8WaZnLXNZlS0j46DlupyRFn1fmWu7E5Olz1SBTRW1PqDx/gObiBDtbhiKdracukO7QVu6bsquk+Sy808T00/XzzV/znZNB+uX2TFspqnIEUo5A3mCcYiyCuK0="
