language: ruby
install:
  - bundle install
script: 'bundle exec rake site:deploy --quiet'
branches:
  except:
    - /^fixture\/.*/
env:
  global:
    secure: >
      "B+Lzmd1+824imHw8cMqw7dzhF4PnaCBKnErtgAfb+V4CYu1vSeSZsH+A2D2ory4TstEX3V3K754B5HOzchrAXJbL19YL6OvUeR0KVLklCL4n3sS5nnxx6tBSbKzwztysQElCV1MeD91fxu4k2WaM7wxSQgAlVxYtBBs1FuKlj/wiXmdL0z44pt1GuZKj/pZI6nJbO8Uvhhzbmv08oXzxyxMfvNF22rc66xAvQelhHmrtrdwrCSRjfRmh4m7WoEprbgP0RQQerzff2K++F366e/YE+4uXAvgngT2AqvjV6T/cxc6Nzqo6OgL1RjGzj73pu1TU+erBExWKN/pcvxflxGJwP74Cy9Q/VSw9jIL9T6ON9Zr71PWO7Vcf1R0TxO9ceJJa1WtJAlANWovDgehC0c9qeAFy2IBlnFsLu/D9+qryLcOM5huotam5Wf2rZP5vYIlDsnL+GLisiWk3bseuUVp+SxTXbcNV+x+A3gyE/s9ul5vudan1nF177MKOOFCqWrXhLHsLga4trYhAeE2e+4fC9h4OVWKysq6UpQOQ3S1X5xe8sdcAdRL82h/rtSBKURyummEtk4UswaM8cvXcr1dvNXE17sI/JxZ83UDpBcsk7xzBk+0NRFKB98C4Y0iBYhO3sZIZKkCpPbti3x3SVuJKPzN7yukOQqFXB/ST/hQ="
