# Dependencies

markdown:         kramdown
# markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Content as Code
tagline:          'Developing workflows and technology to improve content re-use and maintainability.'
description:      'Developing workflows and technology to improve content re-use and maintainability.'
url:              http://iilab.github.io
baseurl:          /contentascode

author:
  name:           'Jun Matsushita'
  url:            https://twitter.com/iilab

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "lax_spacing", "smart"]

github:
  repo:           https://github.com/iilab/contentascode

gems:
  - jekyll-sitemap
  - jekyll-gist

# jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: jmatsushita
owner: iilab
repo: contentascode
#branch: source

# This destination folder is probably not necessary and we should either migrate out of jekyll-travis
# (which might be a good idea to avoid rake+metalsmith+...) or submit a pull request to default this to 
# a temp folder of some sort.

destination: ../build

safe: false
lsi: false
# pygments: true

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml