# Dependencies

markdown:         kramdown
# markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Content as Code
tagline:          'Developing workflows and technology to improve content re-use and maintainability.'
description:      'Developing workflows and technology to improve content re-use and maintainability.'
url:              http://iilab.github.io
baseurl:          /contentascode

author:
  name:           'Jun Matsushita'
  url:            https://twitter.com/iilab

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "lax_spacing", "smart"]

github:
  repo:           https://github.com/iilab/contentascode

gems:
  - jekyll-sitemap
  - jekyll-gist